### PR TITLE
Auto-disable layers that are outside of their minZoom/maxZoom bounds

### PR DESCRIPTION
**Pull request by msiadak**
This should improve the UX a little bit for those that use scale dependency on layers.  Previously, layers would show up as checked when constrained with minZoom and maxZoom but would not draw.

### CODE REVIEW

**Comment by ismyrnow** [comment]
I'm not sure this will always provide a better user experience. Consider when the user zooms in past maxZoom, then zooms back out. The layer gets removed from the map, and the user is forced to re-add it.

I wouldn't recommend doing more than *showing* the user that their layer is out of range, but even that is out of scope for this simple layer control, I think.

**Comment by msiadak** [comment]
That's a good point about having to re-add the layer.  I see that Leaflet master has addressed this issue by adding a _checkDisabledLayers function to L.Control.Layers that only disables the layer inputs without clearing them, as you suggest.  Would you accept a PR that merges in that version of the function?  See https://github.com/Leaflet/Leaflet/commit/723c22312d34d0f4c021909c86f46cad163ca103 for what I'm referring to.

**Comment by ismyrnow** [comment]
If this is in the default Leaflet layer control, getting it added in here would be great. I'd definitely accept a PR for adding that.

**Comment by msiadak** [comment]
Cool, sounds good.  Closing this one; I'll submit a new PR when it's ready.

**Pull request closed without merging**
